name: CI for Scanports library

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build_and_lint:
    runs-on: ubuntu-latest

  steps:
      - uses: actions/checkout@v4
      - name: Checkout and setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '8.x'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run pr:lint
      
      - name: Testing library
        run: npm test